name: Push Docker image to GHCR

on:
  push:
    branches: [ main ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write  # GitHub Appトークンを使用するために必要

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Get the GitHub App token
      id: get_github_app_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.PRIVATE_KEY }}

    - name: Log in to the GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ steps.get_github_app_token.outputs.token }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/sug1t0m0/semver-incrementer:latest
